name: indonesian_words
description: >
  Utilities for working with Indonesian words.
version: 1.0.1
homepage: https://github.com/jerry-maheswara-github/indonesian_words

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  string_scanner: ^1.1.0

dev_dependencies:
  # benchmark_harness: ^1.0.4
  test: ^1.16.8
